name: My after fixture
on:
  repository_dispatch:
    types: [afterFixture]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Check input variables
        run: |
          echo "My input variables: "
          echo ${{ github.event.inputs }}
